//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityBookmark
    {
        public int UniversityId { get; set; }
        public string Description { get; set; }
    }
}
